FROM python:3.9-slim

WORKDIR /app

# Install Robot Framework and RequestsLibrary
RUN pip install robotframework robotframework-requests

COPY txn/integration_tests.robot .

# The tests will be run from this container
CMD ["robot", "integration_tests.robot"]