version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: mysqldatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  txn:
    build:
      context: ../txn
    ports:
      - "8080:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mysqldatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy

  shop:
    build:
      context: ./shop
    ports:
      - "8081:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mysqldatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy

  tests:
    build:
      context: ../txn
      dockerfile: Dockerfile.test
    depends_on:
      - txn
      - shop
volumes:
  db_data: