name: Integration Test Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Checkout shop repository
      uses: actions/checkout@v3
      with:
        repository: 'Comajakit/shop'
        path: 'shop'

    - name: List directory contents for debugging
      run: ls -la

    - name: List directory contents for debugging
      run: ls -la txn

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d
    
    - name: List Docker containers
      run: docker ps

    - name: logs compose
      run: docker-compose logs


    - name: Wait for services to be ready
      run: |
        for i in {1..10}; do
          if curl -s http://txn:8080/health && curl -s http://shop:8081/health; then
            echo "Services are up and running"
            break
          fi
          echo "Waiting for services to be ready..."
          sleep 5
        done

    - name: Run Tests
      run: |
        docker-compose run --rm tests

    - name: Clean up
      if: always()
      run: |
        docker-compose -f docker-compose.yml down
