name: Integration Test Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    # - name: Checkout shop repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: 'Comajakit/shop'
    #     path: 'shop'

    - name: List directory contents for debugging
      run: ls -la



    # - name: List directory contents for debugging
    #   run: ls -la txn

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d
    
    # - name: Build Docker image for testing
    #   run: docker build . -t app

    - name: List Docker containers
      run: docker ps

    # - name: Start App
    #   run: |
    #     docker run --name app app

    # - name: List Docker containers
    #   run: docker ps
      
    # - name: Check txn container status
    #   run: docker ps | grep txn_txn_1
    
    - name: Logs txn
      run: docker-compose logs txn

    - name: Logs txn
      run: docker logs txn_txn_1 -f

    - name: Wait for services to be ready
      run: sleep 20
    
    - name: List Docker containers
      run: docker ps


    - name: Docker Compose logs
      run: docker exec txn_txn_1 curl localhost:8084/api/transactions/status

    # - name: Run Tests
    #   run: |
    #     docker-compose run --rm tests

    # - name: Clean up
    #   if: always()
    #   run: |
    #     docker-compose -f docker-compose.yml down
