name: Integration Test Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Checkout shop repository
      uses: actions/checkout@v3
      with:
        repository: 'Comajakit/shop'
        path: 'shop'

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d

    - name: List Docker containers
      run: docker ps

    - name: Wait for services using Dockerize
      run: |
        docker run --network container:txn_txn_1 jwilder/dockerize \
          -wait tcp://db:3306 \
          -wait http://localhost:8084/api/transactions/status \
          -timeout 1m

        docker run --network container:txn_shop_1 jwilder/dockerize \
          -wait tcp://db:3306 \
          -wait http://localhost:8082/api/shops/status \
          -timeout 1m

    - name: Run Tests
      run: |
        docker-compose run --rm tests

    - name: Clean up
      if: always()
      run: |
        docker-compose -f docker-compose.yml down
